# Generated by Django 3.2.4 on 2021-09-15 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('logo_photo', models.ImageField(blank=True, upload_to='logos_empresas/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release', models.DateTimeField(default=datetime.datetime(2021, 9, 15, 14, 1, 40, 264542, tzinfo=utc))),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/')),
                ('produtora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.produtora')),
            ],
        ),
    ]
